# 개발 언어 및 SDK 설정
language: java
jdk:
  - openjdk8

branches:
  only:
    - master

# Travis CI Server Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.maven'

# mvnw의 실행 권한이 없어서 부여해주어야 한다
before_install:
  - chmod +x mvnw

script: "./mvnw clean package"

# S3 관련 설정 (생성한 jar 파일을 S3 로 보내기)
before_deploy:
  - zip -r freelec-springboot2-webservice
  - mkdir -p deploy
  - mv freelec-springboot2-webservice.zip deploy/freelec-springboot2-webservice.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: freelec-springboot-build-yhh
    region: ap-northeast-2
    cleanup: true # skin_cleanup deprecated 되어있음
    acl: private
    local_dir: deploy
    wait-until-deployed: true

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - harpuria87@gmail.com