language: java
jdk:
  - openjdk8

branches:
  only:
    - master

# Travis CI Server Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.maven'

script: "./mvnw clean package"

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - harpuria87@gmail.com