# 개발 언어 및 SDK 설정
language: java
jdk:
  - openjdk8

branches:
  only:
    - master

# Travis CI Server Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.maven'

# mvnw의 실행 권한이 없어서 부여해주어야 한다
before_install:
  - chmod +x mvnw

script: "./mvnw clean package"

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - harpuria87@gmail.com