version: 0.0 # codeDeploy 버전
os: linux
files:
  - source: / # 루트 경로(/) 를 지정하면 전체 파일을 의미
    destination: /home/ec2-user/app/step3/zip/ # source 에서 지정된 파일을 받을 경로
    overwrite: yes # 덮어쓰기 여부

permissions:
  - object: /
    pattenr: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  AfterInstall:
    - location: stop.sh # Nginx 와 연결되어 있지 않은 스프링부트 종료
      timeout: 60
      runas: ec2-user

  ApplicationStart:
    - location: start.sh # Nginx 와 연결되어 있지 않은 Port로 새 버전의 스프링부트 시작
      timeout: 60
      runas: ec2-user

  ValidateService:
    - location: health.sh # 새 스프링부트가 정상적으로 실행되었는지 확인
      timeout: 60
      runas: ec2-user