version: 0.0 # codeDeploy 버전
os: linux
files:
  - source: / # 루트 경로(/) 를 지정하면 전체 파일을 의미
    destination: /home/ec2-user/app/step2/zip/ # source 에서 지정된 파일을 받을 경로
    overwrite: yes # 덮어쓰기 여부

permissions:
  - object: /
    pattenr: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  ApplicationStart:
    - location: deploy.sh
      timeout: 60
      runas: ec2-user